Imports Microsoft.VisualBasic.Serialization.JSON
Imports Ollama

' ============================================================================
' 模块 8: 整理结果文件（生成 xlsx 表格）
' ============================================================================

''' <summary>
''' 结果表格整理模块。
'''
''' 将分析得到的多个中间结果 csv 表格文件，按照分析的内容主题，
''' 写入到对应的 xlsx 文件之中。
'''
''' 本模块不再由 VB.NET 直接生成 xlsx，而是：
''' 1. 在 VB.NET 中收集所有中间结果 CSV 文件及其第一行表头，并按分析主题分组；
''' 2. 提示 LLM 根据分析主题与历史结论，编写每个工作表第一行（注释说明文本行）的英文注释；
''' 3. 提示 LLM 编写具体的 R 脚本（openxlsx），按规定的样式读取 CSV 并生成 xlsx 结果文件；
''' 4. 由 ShellTool 执行该 R 脚本，完成 xlsx 的生成。
'''
''' xlsx 表格样式要求（写入 LLM 提示词）：
''' - 全局采用 Cambria Math 11 号字体
''' - 表格缩放 90%
''' - 背景色为默认的白色
''' - 第一列（id 列）：浅灰色背景色，斜体，黑色字体颜色
''' - 第一行（注释说明文本行）：默认背景色，草绿色字体颜色
''' - 第二行（列标题行）：深蓝色背景色，白色字体颜色，加粗字体
''' - 第一列 + 第二行进行 freeze panes 冻结
''' - 所有文本信息（文件名、注释、标题、列标题）均为英文
''' </summary>
Public Class ResultTablesModule : Inherits AnalysisModuleBase

    Public Overrides ReadOnly Property ModuleName As String = "Result Tables Compilation"
    Public Overrides ReadOnly Property ModuleIndex As Integer = 8

    Public Sub New(config As AgentConfig, context As AnalysisContext, llmFactory As Func(Of LLMClient), Optional logger As Action(Of String) = Nothing)
        MyBase.New(config, context, llmFactory, logger)
    End Sub

    Protected Overrides Async Function GeneratePlanAsync(cancellationToken As CancellationToken) As Task(Of ModulePlan)
        Using llm = _llmFactory()
            RegisterTools(llm)

            Dim prompt = $"
You are a bioinformatics data analyst. Design a plan to compile result tables.

{BuildContextInfo()}

# Your Task
Design a plan to compile all intermediate CSV result tables into organized XLSX files.
1. Scan all CSV files in tmp/ and analysis_modules_*/tables/ directories
2. Group them by analysis theme:
   - Preprocessing results
   - PCA/PLSDA/OPLSDA results
   - Differential analysis results (limma)
   - KEGG enrichment and GSVA results
   - WGCNA module results
   - Advanced analysis results (CMeans, Bayesian, PLS-PM)
3. For each group, create an XLSX file with multiple sheets
4. Each sheet should have:
   - Row 1: Description/annotation text (forest green font)
   - Row 2: Column headers (dark blue background, white bold font)
   - Row 3+: Data
   - First column: light gray background, italic, black font
   - Freeze panes at B3
The actual XLSX files will be generated by an R script (openxlsx) written by the LLM later.

Return your plan as JSON:
{{
  ""module_name"": ""Result Tables Compilation"",
  ""goal"": ""<brief description>"",
  ""input_files"": [""<input file paths>""],
  ""output_files"": [""<expected output file paths>""],
  ""notes"": ""<special considerations>""
}}
"
            Dim resp = Await llm.Chat(prompt, cancellationToken)
            Dim json = ExtractJsonFromResponse(resp.output)
            Dim plan As ModulePlan
            If Not String.IsNullOrEmpty(json) Then
                plan = json.LoadJSON(Of ModulePlan)
            Else
                plan = New ModulePlan() With {.ModuleName = ModuleName, .Goal = resp.output}
            End If
            plan.ModuleName = ModuleName
            Return plan
        End Using
    End Function

    Protected Overrides Async Function GenerateAndRunScriptAsync(plan As ModulePlan, cancellationToken As CancellationToken) As Task
        LogInfo("Compiling result tables into XLSX files via LLM-generated R script...")

        ' 1. 收集所有 CSV 结果文件并按分析主题分组
        Dim csvFiles = CollectResultCsvFiles()
        Dim groupedFiles = GroupCsvByTheme(csvFiles)

        If groupedFiles.Count = 0 Then
            LogInfo("No CSV result files found. Skipping XLSX generation.")
            Return
        End If

        ' 2. 第一次 LLM 调用：生成每个 sheet 第一行的英文注释说明，保存为 JSON
        Dim descJson = Await GenerateAnnotationsAsync(groupedFiles, cancellationToken)
        Dim descPath = Path.Combine(_context.WorkspaceDir, "analysis", "table_descriptions.json")
        PathUtils.WriteAllText(descPath, descJson)
        LogInfo($"Table descriptions saved: {descPath}")

        ' 3. 第二次 LLM 调用：编写生成 xlsx 的 R 脚本并执行
        Using llm = _llmFactory()
            RegisterTools(llm)

            Dim analysisDir = Path.Combine(_context.WorkspaceDir, "analysis")
            Dim prompt = BuildRScriptPrompt(descPath, analysisDir)

            Dim resp = Await llm.Chat(prompt, cancellationToken)
            Dim rCode = ExtractCodeBlock(resp.output, "r")

            Dim scriptFile = Path.Combine(_context.ScriptsDir, $"module_{ModuleIndex}_result_tables.R")
            PathUtils.WriteAllText(scriptFile, rCode)

            Dim shell As New ShellTool(_config, _context.WorkspaceDir, _logger)
            Dim result = shell.run_rscript($"scripts/module_{ModuleIndex}_result_tables.R", timeout_seconds:=600)
            LogInfo($"R script execution result: {result.Substring(0, Math.Min(500, result.Length))}")
        End Using
    End Function

    Protected Overrides Async Function GenerateConclusionAsync(plan As ModulePlan, cancellationToken As CancellationToken) As Task(Of String)
        Return Await Task.FromResult("结果表格已整理完成：VB.NET 收集了所有中间结果 CSV 文件及其表头并按分析主题分组，先由 LLM 编写了每个工作表第一行的英文注释说明，再由 LLM 编写 openxlsx R 脚本生成了对应的 XLSX 文件。每个 XLSX 文件包含多个工作表，每个工作表的第一行为表格注释说明（草绿色字体），第二行为列标题（深蓝色背景白色加粗字体），第一列为分子 ID（浅灰色背景斜体），并已冻结窗格，全局采用 Cambria Math 11 号字体、缩放 90%。")
    End Function

    ''' <summary>收集所有结果 CSV 文件</summary>
    Private Function CollectResultCsvFiles() As List(Of String)
        Dim result As New List(Of String)()
        Dim analysisDir = Path.Combine(_context.WorkspaceDir, "analysis")
        If Not Directory.Exists(analysisDir) Then Return result

        ' 收集 tmp/ 目录下的 CSV 文件
        Dim tmpDir = Path.Combine(_context.WorkspaceDir, "tmp")
        If Directory.Exists(tmpDir) Then
            result.AddRange(Directory.GetFiles(tmpDir, "*.csv"))
        End If

        ' 收集各模块 tables/ 目录下的 CSV 文件
        For Each dir As String In Directory.GetDirectories(analysisDir, "analysis_modules_*")
            Dim tablesDir = Path.Combine(dir, "tables")
            If Directory.Exists(tablesDir) Then
                result.AddRange(Directory.GetFiles(tablesDir, "*.csv"))
            End If
        Next

        Return result
    End Function

    ''' <summary>按分析主题分组 CSV 文件</summary>
    Private Function GroupCsvByTheme(csvFiles As List(Of String)) As Dictionary(Of String, List(Of String))
        Dim groups As New Dictionary(Of String, List(Of String)) From {
            {"Preprocessing_Results", New List(Of String)},
            {"PCA_Results", New List(Of String)},
            {"LIMMA_Differential_Results", New List(Of String)},
            {"KEGG_Functional_Results", New List(Of String)},
            {"WGCNA_Module_Results", New List(Of String)},
            {"Advanced_Analysis_Results", New List(Of String)}
        }

        For Each csv In csvFiles
            Dim name = Path.GetFileName(csv).ToLower()
            If name.Contains("preprocess") Or name.Contains("normalized") Then
                groups("Preprocessing_Results").Add(csv)
            ElseIf name.Contains("pca") Or name.Contains("plsda") Or name.Contains("oplsda") Then
                groups("PCA_Results").Add(csv)
            ElseIf name.Contains("diff") Or name.Contains("limma") Or name.Contains("anova") Or name.Contains("volcano") Then
                groups("LIMMA_Differential_Results").Add(csv)
            ElseIf name.Contains("kegg") Or name.Contains("gsva") Or name.Contains("enrich") Then
                groups("KEGG_Functional_Results").Add(csv)
            ElseIf name.Contains("wgcna") Or name.Contains("module") Or name.Contains("eigengene") Then
                groups("WGCNA_Module_Results").Add(csv)
            ElseIf name.Contains("cmeans") Or name.Contains("cluster") Or name.Contains("bayesian") Or name.Contains("plspm") Or name.Contains("bnlearn") Then
                groups("Advanced_Analysis_Results").Add(csv)
            Else
                ' 默认放入 LIMMA 差异分析结果
                groups("LIMMA_Differential_Results").Add(csv)
            End If
        Next

        ' 移除空组
        Dim toRemove = groups.Where(Function(g) g.Value.Count = 0).Select(Function(g) g.Key).ToList()
        For Each key In toRemove
            groups.Remove(key)
        Next

        Return groups
    End Function

    ''' <summary>读取 CSV 文件的第一行表头</summary>
    Private Function GetCsvHeader(csvPath As String) As List(Of String)
        Dim result As New List(Of String)()
        Try
            Dim firstLine = File.ReadLines(csvPath).FirstOrDefault()
            If Not String.IsNullOrEmpty(firstLine) Then
                result.AddRange(firstLine.Split(","c))
            End If
        Catch
        End Try
        Return result
    End Function

    ''' <summary>将主题键转换为英文展示名</summary>
    Private Function ThemeDisplayName(themeKey As String) As String
        Select Case themeKey
            Case "Preprocessing_Results" : Return "Preprocessing Results"
            Case "PCA_Results" : Return "PCA/PLSDA/OPLSDA Results"
            Case "LIMMA_Differential_Results" : Return "LIMMA Differential Analysis Results"
            Case "KEGG_Functional_Results" : Return "KEGG Functional Analysis Results"
            Case "WGCNA_Module_Results" : Return "WGCNA Module Results"
            Case "Advanced_Analysis_Results" : Return "Advanced Analysis Results"
            Case Else : Return themeKey.Replace("_"c, " ")
        End Select
    End Function

    ''' <summary>清洗工作表名称，符合 Excel 限制（&lt;=31 字符，无非法字符）</summary>
    Private Function SanitizeSheetName(name As String) As String
        Dim s = Path.GetFileNameWithoutExtension(name)
        If s.Length > 31 Then s = s.Substring(0, 31)
        s = s.Replace(":"c, "_"c).Replace("\"c, "_"c).Replace("/"c, "_"c).Replace("?"c, "_"c).Replace("*"c, "_"c).Replace("["c, "_"c).Replace("]"c, "_"c)
        Return s
    End Function

    ''' <summary>
    ''' 第一次 LLM 调用：根据分析主题、CSV 表头与历史结论，
    ''' 生成每个 sheet 第一行（注释说明文本行）的英文注释，并保存为结构化 JSON。
    ''' </summary>
    Private Async Function GenerateAnnotationsAsync(groupedFiles As Dictionary(Of String, List(Of String)), cancellationToken As CancellationToken) As Task(Of String)
        ' 构建骨架 JSON（含 csv 绝对路径、英文 sheet 名、空注释）
        Dim sk As New StringBuilder()
        sk.AppendLine("{")
        sk.AppendLine("  ""xlsx_files"": [")
        Dim firstGroup = True
        For Each grp In groupedFiles
            If Not firstGroup Then sk.AppendLine("    },")
            firstGroup = False
            sk.AppendLine("    {")
            sk.AppendLine($"      ""file"": ""{grp.Key}.xlsx"",")
            sk.AppendLine($"      ""theme"": ""{ThemeDisplayName(grp.Key)}"",")
            sk.AppendLine($"      ""sheets"": [")
            Dim firstSheet = True
            For Each csv In grp.Value
                If Not firstSheet Then sk.AppendLine("        },")
                firstSheet = False
                sk.AppendLine("        {")
                sk.AppendLine($"          ""csv"": ""{csv}"",")
                sk.AppendLine($"          ""sheet_name"": ""{SanitizeSheetName(csv)}"",")
                sk.AppendLine($"          ""annotation"": """"")
            Next
            If grp.Value.Count > 0 Then sk.AppendLine("        }")
            sk.AppendLine("      ]")
        Next
        If groupedFiles.Count > 0 Then sk.AppendLine("    }")
        sk.AppendLine("  ]")
        sk.AppendLine("}")

        Dim skeleton = sk.ToString()

        Using llm = _llmFactory()
            RegisterTools(llm)

            ' 构建每个 sheet 的表头信息，供 LLM 编写注释
            Dim headersInfo As New StringBuilder()
            For Each grp In groupedFiles
                headersInfo.AppendLine($"## Theme: {ThemeDisplayName(grp.Key)} (XLSX file: {grp.Key}.xlsx)")
                For Each csv In grp.Value
                    Dim hdr = GetCsvHeader(csv)
                    headersInfo.AppendLine($"- CSV: {Path.GetFileName(csv)}")
                    headersInfo.AppendLine($"  Sheet name: {SanitizeSheetName(csv)}")
                    headersInfo.AppendLine($"  Columns ({hdr.Count}): {String.Join(", ", hdr)}")
                Next
            Next

            Dim prompt As String = <root><![CDATA[
You are a bioinformatics data analyst. Your task is to write English annotation text for the FIRST ROW of each sheet in a set of result XLSX files.

# Research Context
{CONTEXT}

# CSV files to be compiled (grouped by theme)
{HEADERS}

# Table descriptions skeleton (JSON)
The following JSON lists the XLSX files to create and the CSV files (sheets) each contains. The 'annotation' fields are currently EMPTY.

{SKELETON}

# Your Task
For EACH sheet, fill in the 'annotation' field (a string) with a clear English description that will be placed in the FIRST ROW of that sheet. The annotation must:
- Explain what data / contents this table contains.
- Explain the meaning of EACH column (use the column list provided above for that CSV).
- Explain what biological knowledge / insights a user can gain from this table.
Keep it informative but concise (typically 2-5 sentences). You MAY also refine 'sheet_name' to a clearer English name (<=31 chars, without : \ / ? * [ ] characters), but you MUST keep the 'csv' absolute path EXACTLY as given.

Return ONLY the completed JSON (no extra explanation, no markdown code fences).
]]></root>.Value

            prompt = prompt.Replace("{CONTEXT}", BuildContextInfo()) _
                           .Replace("{HEADERS}", headersInfo.ToString()) _
                           .Replace("{SKELETON}", skeleton)

            Dim resp = Await llm.Chat(prompt, cancellationToken)
            Dim json = ExtractJsonFromResponse(resp.output)
            If Not String.IsNullOrEmpty(json) Then
                Return json
            End If
        End Using

        ' LLM 调用失败时回退到骨架（注释为空），保证 R 脚本仍可运行
        Return skeleton
    End Function

    ''' <summary>
    ''' 构建第二次 LLM 调用的提示词：要求 LLM 编写基于 openxlsx 的 R 脚本，
    ''' 按规定的样式读取 CSV 与注释 JSON，生成 xlsx 结果文件。
    ''' </summary>
    Private Function BuildRScriptPrompt(descPath As String, analysisDir As String) As String
        Dim prompt As String = <root><![CDATA[
You are a bioinformatics R scripting expert. Write a complete R script that compiles multiple intermediate CSV result tables into organized, styled XLSX files using the openxlsx package.

# Inputs
- A JSON file at: {DESC_PATH}
  describes which XLSX files to create, which CSV files (sheets) each contains, and an English annotation text for the first row of each sheet.
- Output directory for XLSX files: {OUT_DIR}

# JSON structure (table_descriptions.json)
{
  'xlsx_files': [
    {
      'file': 'Preprocessing_Results.xlsx',
      'theme': 'Preprocessing Results',
      'sheets': [
        { 'csv': '<absolute csv path>', 'sheet_name': '<english sheet name>', 'annotation': '<english annotation text for row 1>' }
      ]
    }
  ]
}

# Your Task
Write an R script that:
1. Ensures the openxlsx package is available (use: if (!require(openxlsx)) install.packages('openxlsx'); library(openxlsx)). Also ensure jsonlite is available the same way.
2. Reads the JSON with jsonlite::fromJSON('{DESC_PATH}', simplifyVector = TRUE).
3. For each entry in xlsx_files:
   a. Create a new workbook: wb <- createWorkbook()
   b. For each sheet entry:
      - Read the CSV: df <- read.csv(sh$csv, stringsAsFactors = FALSE, check.names = FALSE)
      - Add a worksheet with a valid English sheet name (<=31 chars, no : \ / ? * [ ] characters): addWorksheet(wb, sheetName = sh$sheet_name)
      - Write the annotation text into cell A1 (row 1): writeData(wb, sh$sheet_name, x = sh$annotation, startRow = 1, startCol = 1, colNames = FALSE, rowNames = FALSE)
      - Write the CSV column headers into row 2: writeData(wb, sh$sheet_name, x = as.data.frame(t(colnames(df))), startRow = 2, startCol = 1, colNames = FALSE, rowNames = FALSE)
      - Write the CSV data (without its header) starting at row 3, column 1: writeData(wb, sh$sheet_name, x = df, startRow = 3, startCol = 1, colNames = FALSE, rowNames = FALSE)
   c. Define and apply the following styles (ALL using font name 'Cambria Math', size 11):
      - defaultStyle: Cambria Math 11, default white background. Apply to the whole used range first.
      - annotStyle: default background, forest green font color '#228B22'. Apply to row 1 (all used columns).
      - headerStyle: dark blue background '#1F4E79', white font '#FFFFFF', bold textDecoration = 'bold'. Apply to row 2 (all used columns).
      - idStyle: light gray background '#D9D9D9', italic textDecoration = 'italic', black font '#000000'. Apply to the first column (column A), rows 3 to last data row.
      Apply defaultStyle first, then overlay annotStyle / headerStyle / idStyle so specific styles win.
   d. Freeze the first column AND the first two rows (TopLeft cell = B3). In openxlsx: freezePane(wb, sh$sheet_name, firstRow = 3, firstCol = 2)
   e. Set sheet zoom to 90%: setZoom(wb, sh$sheet_name, zoom = 90)
   f. Save the workbook: saveWorkbook(wb, file.path('{OUT_DIR}', fi$file), overwrite = TRUE)
4. Print progress messages and handle missing files gracefully (skip and warn, do not stop).
5. IMPORTANT: All text (XLSX file names, sheet names, annotations, column headers) MUST be in English.

# Reference template (adapt as needed)
library(openxlsx)
if (!require(openxlsx)) install.packages('openxlsx')
if (!require(jsonlite)) install.packages('jsonlite')
library(openxlsx)
library(jsonlite)

desc <- fromJSON('{DESC_PATH}', simplifyVector = TRUE)
out_dir <- '{OUT_DIR}'

defaultStyle <- createStyle(fontName = 'Cambria Math', fontSize = 11)
annotStyle <- createStyle(fontName = 'Cambria Math', fontSize = 11, fontColour = '#228B22')
headerStyle <- createStyle(fontName = 'Cambria Math', fontSize = 11, fontColour = 'FFFFFF', fgFill = '#1F4E79', textDecoration = 'bold')
idStyle <- createStyle(fontName = 'Cambria Math', fontSize = 11, fgFill = '#D9D9D9', textDecoration = 'italic', fontColour = '000000')

for (i in seq_along(desc$xlsx_files)) {
  fi <- desc$xlsx_files[[i]]
  wb <- createWorkbook()
  for (j in seq_along(fi$sheets)) {
    sh <- fi$sheets[[j]]
    if (!file.exists(sh$csv)) { warning(paste('Missing CSV:', sh$csv)); next }
    df <- read.csv(sh$csv, stringsAsFactors = FALSE, check.names = FALSE)
    ncol <- ncol(df)
    lastRow <- nrow(df) + 2
    addWorksheet(wb, sheetName = sh$sheet_name)
    writeData(wb, sh$sheet_name, x = sh$annotation, startRow = 1, startCol = 1, colNames = FALSE, rowNames = FALSE)
    writeData(wb, sh$sheet_name, x = as.data.frame(t(colnames(df))), startRow = 2, startCol = 1, colNames = FALSE, rowNames = FALSE)
    writeData(wb, sh$sheet_name, x = df, startRow = 3, startCol = 1, colNames = FALSE, rowNames = FALSE)
    addStyle(wb, sh$sheet_name, defaultStyle, rows = 1:lastRow, cols = 1:ncol, gridExpand = TRUE)
    addStyle(wb, sh$sheet_name, annotStyle, rows = 1, cols = 1:ncol, gridExpand = TRUE)
    addStyle(wb, sh$sheet_name, headerStyle, rows = 2, cols = 1:ncol, gridExpand = TRUE)
    addStyle(wb, sh$sheet_name, idStyle, rows = 3:lastRow, cols = 1, gridExpand = TRUE)
    freezePane(wb, sh$sheet_name, firstRow = 3, firstCol = 2)
    setZoom(wb, sh$sheet_name, zoom = 90)
    cat(paste('Prepared sheet', sh$sheet_name, 'for', fi$file, '\n'))
  }
  saveWorkbook(wb, file.path(out_dir, fi$file), overwrite = TRUE)
  cat(paste('Saved', fi$file, '\n'))
}

# Important Notes
- Use absolute paths.
- Make sure numeric columns remain numeric (do not wrap them as text).
- The script must run end-to-end without further input.

Write the complete R script inside a ```r ... ``` code block.
]]></root>.Value

        prompt = prompt.Replace("{DESC_PATH}", descPath).Replace("{OUT_DIR}", analysisDir)
        Return prompt
    End Function

    Private Function ExtractJsonFromResponse(text As String) As String
        If String.IsNullOrEmpty(text) Then Return ""
        Dim match = System.Text.RegularExpressions.Regex.Match(text, "```(?:json)?\s*([\s\S]*?)```")
        If match.Success Then Return match.Groups(1).Value.Trim()
        Dim startIdx = text.IndexOf("{"c)
        Dim endIdx = text.LastIndexOf("}"c)
        If startIdx >= 0 AndAlso endIdx > startIdx Then Return text.Substring(startIdx, endIdx - startIdx + 1)
        Return ""
    End Function

End Class
