file_path <- "G:/OmicsWorks/test/metabolism/demo/scripts/module_2_pca_plsda_oplsda.R"
lines <- readLines(file_path, warn = FALSE)

# Find the problematic PLSDA section and replace it
# Section starts around ">>>6. PLSDA Analysis" and ends at ">>>7. OPLSDA Analysis"

# Find line numbers for replacement
start_line <- grep(">>>6. PLSDA Analysis", lines)[1]
end_line <- grep(">>>7. OPLSDA Analysis", lines)[1]

cat("PLSDA section from line", start_line, "to", end_line, "\n")

# Build replacement for the PLSDA section
new_plsda_section <- c(
 '# ----6. PLSDA Analysis (mixOmics) ----',
 'cat("\\n========================================\\n")',
 'cat(">>>6. PLSDA Analysis (mixOmics)\\n")',
 'cat("========================================\\n")',
 '',
 'plsda_model <- plsda(t(expr_matrix), groups, ncomp =3)',
 'plsda_scores <- as.data.frame(plsda_model$variates$X[,1:3])',
 'colnames(plsda_scores) <- c("comp1", "comp2", "comp3")',
 '',
 '# Handle explained variance (may be NULL in some mixOmics versions)',
 'if (!is.null(plsda_model$explained_variance$X)) {',
 ' plsda_var <- as.numeric(plsda_model$explained_variance$X[1:3]) *100',
 '} else {',
 ' plsda_var <- rep(NA_real_,3)',
 '}',
 'if (any(is.na(plsda_var))) {',
 ' # Fallback: use variance of score columns',
 ' score_var <- apply(plsda_scores,2, var)',
 ' plsda_var <- score_var / sum(score_var) *100',
 '}',
 'cat(sprintf(" Component1: %.2f%%, Component2: %.2f%%, Component3: %.2f%%\\n",',
 ' plsda_var[1], plsda_var[2], plsda_var[3]))',
 '',
 '# Save scores',
 'plsda_out <- data.frame(',
 ' sample = rownames(plsda_scores),',
 ' group = groups,',
 ' comp1 = plsda_scores$comp1,',
 ' comp2 = plsda_scores$comp2,',
 ' comp3 = plsda_scores$comp3,',
 ' stringsAsFactors = FALSE',
 ')',
 'write.csv(plsda_out, file.path(output_dir, "tables", "plsda_scores.csv"), row.names = FALSE)',
 'cat(" -> plsda_scores.csv saved\\n")',
 '',
 '# VIP scores',
 'vip <- vip(plsda_model)',
 'vip_df <- data.frame(',
 ' molecule = rownames(vip),',
 ' VIP = as.numeric(vip[,1]),',
 ' stringsAsFactors = FALSE',
 ')',
 'vip_df <- vip_df[order(-vip_df$VIP), ]',
 'write.csv(vip_df, file.path(output_dir, "tables", "plsda_vip_scores.csv"), row.names = FALSE)',
 'cat(sprintf(" VIP >1: %d, VIP >1.5: %d, VIP >2: %d\\n",',
 ' sum(vip_df$VIP >1), sum(vip_df$VIP >1.5), sum(vip_df$VIP >2)))',
 '',
 '# PLSDA distance & permutation',
 'plsda_dist <- calc_weighted_dist(as.matrix(plsda_scores), plsda_var, groups)',
 'plsda_perm <- permutation_test(as.matrix(plsda_scores), groups, plsda_var, n_perm)',
 'cat(sprintf(" Permutation: observed ratio=%.4f, p=%.4f\\n",',
 ' plsda_perm$observed_ratio, plsda_perm$p_value))',
 '',
 '# ----6a. PLSDA Score Plot ----',
 'p_plsda <- ggplot(plsda_out, aes(x = comp1, y = comp2, color = group, shape = group)) +',
 ' geom_point(size =4, alpha =0.85) +',
 ' stat_ellipse(level =0.95, type = "norm", size =1, alpha =0.5) +',
 ' scale_color_manual(values = group_colors) +',
 ' scale_shape_manual(values = group_shapes) +',
 ' geom_text_repel(aes(label = sample), size =3, max.overlaps =15, show.legend = FALSE) +',
 ' labs(',
 ' x = sprintf("Component1 (%.1f%%)", plsda_var[1]),',
 ' y = sprintf("Component2 (%.1f%%)", plsda_var[2]),',
 ' title = "PLSDA Score Plot",',
 ' color = "Group", shape = "Group"',
 ' ) +',
 ' theme_pub()',
 '',
 'ggsave(file.path(output_dir, "figures", "plsda_score_plot.png"),',
 ' p_plsda, width =8, height =6, dpi =300)',
 'ggsave(file.path(output_dir, "figures", "plsda_score_plot.pdf"),',
 ' p_plsda, width =8, height =6)',
 'cat(" -> plsda_score_plot saved\\n")',
 '',
 '# ----6b. PLSDA VIP Plot (top30) ----',
 'top30_vip <- vip_df[1:min(30, nrow(vip_df)), ]',
 'top30_vip$molecule <- factor(top30_vip$molecule, levels = rev(top30_vip$molecule))',
 'top30_vip$color_group <- ifelse(',
 ' top30_vip$VIP >2, "VIP >2",',
 ' ifelse(top30_vip$VIP >1.5, "VIP1.5-2", "VIP1-1.5")',
 ')',
 '',
 'p_vip <- ggplot(top30_vip, aes(x = molecule, y = VIP, fill = color_group)) +',
 ' geom_bar(stat = "identity", width =0.7) +',
 ' scale_fill_manual(',
 ' values = c("VIP >2" = "#D73027", "VIP1.5-2" = "#FDAE61", "VIP1-1.5" = "#ABD9E9")',
 ' ) +',
 ' geom_hline(yintercept =1, linetype = "dashed", color = "grey50") +',
 ' coord_flip() +',
 ' labs(',
 ' x = "Metabolite",',
 ' y = "VIP Score",',
 ' title = "PLSDA: Top30 VIP Metabolites",',
 ' fill = "VIP Category"',
 ' ) +',
 ' theme_pub(base_size =12)',
 '',
 'ggsave(file.path(output_dir, "figures", "plsda_vip_plot.png"),',
 ' p_vip, width =10, height =8, dpi =300)',
 'ggsave(file.path(output_dir, "figures", "plsda_vip_plot.pdf"),',
 ' p_vip, width =10, height =8)',
 'cat(" -> plsda_vip_plot saved\\n")',
 '',
 '# ----6c. PLSDA Cross-validation ----',
 'cat(">>> PLSDA cross-validation...\\n")',
 'set.seed(456)',
 '# With only6 samples per group, use leave-one-out to avoid Mfold errors',
 'plsda_cv <- tryCatch({',
 ' perf(plsda_model, validation = "Mfold", folds =5, nrepeat =3, dist = "max.dist")',
 '}, error = function(e) {',
 ' cat(" Mfold CV failed, trying leave-one-out...\\n")',
 ' perf(plsda_model, validation = "loo", dist = "max.dist")',
 '})',
 '',
 'cv_summary <- tryCatch({',
 ' data.frame(',
 ' comp =1:3,',
 ' BER = as.numeric(plsda_cv$error.rate$BER[1, ]),',
 ' overall_error = as.numeric(plsda_cv$error.rate$overall[1, ])',
 ' )',
 '}, error = function(e) {',
 ' data.frame(comp =1:3, BER = NA, overall_error = NA)',
 '})',
 '',
 'write.csv(cv_summary, file.path(output_dir, "tables", "plsda_cv_results.csv"),',
 ' row.names = FALSE)',
 'if (!is.na(cv_summary$BER[1])) {',
 ' cat(sprintf(" CV BER: %.3f, %.3f, %.3f\\n", cv_summary$BER[1], cv_summary$BER[2], cv_summary$BER[3]))',
 '} else {',
 ' cat(" CV BER: NA (cross-validation failed)\\n")',
 '}'
)

# Replace the section
lines <- c(lines[1:(start_line-1)], new_plsda_section, lines[(end_line):length(lines)])

writeLines(lines, file_path)
cat("PLSDA section replaced.\n")
