file_path <- "G:/OmicsWorks/test/metabolism/demo/scripts/module_2_pca_plsda_oplsda.R"
lines <- readLines(file_path, warn = FALSE)

# Find OPLSDA section start
start_line <- grep(">>>7. OPLSDA Analysis", lines)[1]
# Find the end: after OPLSDA, look for ">>>8. Permutation" or similar
end_line <- grep(">>>8. Permutation Test Summary", lines)[1]

cat("OPLSDA section: lines", start_line, "to", end_line, "\n")

# Build replacement OPLSDA section
# Since ropls::opls only supports binary classification for OPLSDA,
# we'll use mixOmics::splsda as the primary approach (sparse PLS-DA as OPLSDA-like),
# and also try ropls::opls for one-vs-rest if needed.

new_oplsda_section <- c(
 '# ----7. OPLSDA Analysis ----',
 'cat("\\n========================================\\n")',
 'cat(">>>7. OPLSDA Analysis\\n")',
 'cat("========================================\\n")',
 '',
 '# ropls::opls only supports binary classification for OPLS-DA.',
 '# With3 groups, we use two approaches:',
 '#1. mixOmics::splsda as OPLSDA-like (sparse PLS-DA with orthogonal components)',
 '#2. If only2 groups exist, ropls::opls is used',
 '',
 'if (nlevels(groups) ==2) {',
 ' cat(">>> Using ropls::opls (binary classification)\\n")',
 ' X_mat <- t(expr_matrix)',
 ' Y_fac <- groups',
 ' oplsda_model <- opls(',
 ' x = X_mat,',
 ' y = Y_fac,',
 ' predI =1,',
 ' orthoI =2',
 ' )',
 '} else {',
 ' cat(">>> Using mixOmics::splsda for multi-group OPLSDA-like analysis\\n")',
 ' # Tune keepX parameters',
 ' set.seed(123)',
 ' tune_result <- tryCatch({',
 ' tune.splsda(t(expr_matrix), groups, ncomp =3,',
 ' test.keepX = c(seq(5,50,5), seq(60,100,20)),',
 ' validation = "Mfold", folds =5, nrepeat =1,',
 ' dist = "max.dist")',
 ' }, error = function(e) {',
 ' cat(" Warning: tune.splsda failed:", e$message, "\\n")',
 ' NULL',
 ' })',
 ' if (!is.null(tune_result)) {',
 ' optimal_keepX <- tune_result$choice.keepX',
 ' } else {',
 ' optimal_keepX <- rep(50,3)',
 ' }',
 ' cat(" Optimal keepX:", optimal_keepX, "\\n")',
 ' oplsda_model <- splsda(t(expr_matrix), groups, ncomp =3, keepX = optimal_keepX)',
 '}',
 '',
 '# Extract scores and variance',
 'if (inherits(oplsda_model, "opls")) {',
 ' # ropls model',
 ' oplsda_score_matrix <- oplsda_model@scoreMN',
 ' n_ortho <- ncol(oplsda_score_matrix) -1',
 ' oplsda_scores <- data.frame(',
 ' predictive = oplsda_score_matrix[,1],',
 ' stringsAsFactors = FALSE',
 ' )',
 ' if (n_ortho >=1) oplsda_scores$orthogonal1 <- oplsda_score_matrix[,2]',
 ' if (n_ortho >=2) oplsda_scores$orthogonal2 <- oplsda_score_matrix[,3]',
 ' rownames(oplsda_scores) <- rownames(oplsda_score_matrix)',
 ' oplsda_var <- oplsda_model@modelDF$R2X *100',
 ' if (length(oplsda_var) <3) oplsda_var <- c(oplsda_var, rep(0,3 - length(oplsda_var)))',
 ' ',
 ' oplsda_summary <- data.frame(',
 ' Metric = c("R2X", "R2Y", "Q2"),',
 ' Value = c(',
 ' oplsda_model@modelDF["total", "R2X"],',
 ' oplsda_model@modelDF["total", "R2Y"],',
 ' oplsda_model@modelDF["total", "Q2"]',
 ' )',
 ' )',
 ' cat(sprintf(" R2X = %.4f, R2Y = %.4f, Q2 = %.4f\\n",',
 ' oplsda_summary$Value[1], oplsda_summary$Value[2], oplsda_summary$Value[3]))',
 ' cat(sprintf(" Predictive R2X: %.2f%%\\n", oplsda_var[1]))',
 ' ',
 ' # OPLSDA VIP (from ropls)',
 ' oplsda_vip_df <- data.frame(',
 ' molecule = names(oplsda_model@vipVn),',
 ' VIP = as.numeric(oplsda_model@vipVn),',
 ' stringsAsFactors = FALSE',
 ' )',
 '} else if (inherits(oplsda_model, "splsda")) {',
 ' # mixOmics sPLSDA model',
 ' oplsda_scores_full <- as.data.frame(oplsda_model$variates$X[,1:3])',
 ' colnames(oplsda_scores_full) <- c("predictive", "orthogonal1", "orthogonal2")',
 ' oplsda_scores <- oplsda_scores_full',
 ' oplsda_var <- as.numeric(oplsda_model$explained_variance$X[1:3]) *100',
 ' if (any(is.na(oplsda_var))) {',
 ' score_var <- apply(oplsda_scores,2, var, na.rm = TRUE)',
 ' oplsda_var <- score_var / sum(score_var) *100',
 ' }',
 ' if (length(oplsda_var) <3) oplsda_var <- c(oplsda_var, rep(0,3 - length(oplsda_var)))',
 ' ',
 ' oplsda_summary <- data.frame(',
 ' Metric = c("Comp1", "Comp2", "Comp3"),',
 ' Value = oplsda_var',
 ' )',
 ' cat(sprintf(" Predictive: %.2f%%, Orthogonal1: %.2f%%, Orthogonal2: %.2f%%\\n",',
 ' oplsda_var[1], oplsda_var[2], oplsda_var[3]))',
 ' ',
 ' # VIP from sPLSDA',
 ' oplsda_vip <- tryCatch(vip(oplsda_model), error = function(e) NULL)',
 ' if (!is.null(oplsda_vip)) {',
 ' oplsda_vip_df <- data.frame(',
 ' molecule = rownames(oplsda_vip),',
 ' VIP = as.numeric(oplsda_vip[,1]),',
 ' stringsAsFactors = FALSE',
 ' )',
 ' } else {',
 ' oplsda_vip_df <- data.frame(molecule = rownames(expr_matrix), VIP = NA)',
 ' }',
 '} else {',
 ' stop("OPLSDA model is NULL - analysis failed")',
 '}',
 '',
 'oplsda_vip_df <- oplsda_vip_df[order(-oplsda_vip_df$VIP), ]',
 'write.csv(oplsda_vip_df, file.path(output_dir, "tables", "oplsda_vip_scores.csv"),',
 ' row.names = FALSE)',
 '',
 '# Save OPLSDA scores',
 'oplsda_out <- data.frame(',
 ' sample = rownames(oplsda_scores),',
 ' group = groups,',
 ' predictive = oplsda_scores$predictive,',
 ' orthogonal1 = ifelse("orthogonal1" %in% colnames(oplsda_scores),',
 ' oplsda_scores$orthogonal1, NA),',
 ' orthogonal2 = ifelse("orthogonal2" %in% colnames(oplsda_scores),',
 ' oplsda_scores$orthogonal2, NA),',
 ' stringsAsFactors = FALSE',
 ')',
 'write.csv(oplsda_out, file.path(output_dir, "tables", "oplsda_scores.csv"),',
 ' row.names = FALSE)',
 'cat(" -> oplsda_scores.csv saved\\n")',
 '',
 '# OPLSDA distance & permutation',
 'oplsda_score_mat <- as.matrix(oplsda_scores[, c("predictive", "orthogonal1", "orthogonal2")])',
 'oplsda_score_mat[is.na(oplsda_score_mat)] <-0',
 'oplsda_dist <- calc_weighted_dist(oplsda_score_mat, oplsda_var[1:3], groups)',
 'oplsda_perm <- permutation_test(oplsda_score_mat, groups, oplsda_var[1:3], n_perm)',
 'cat(sprintf(" Permutation: observed ratio=%.4f, p=%.4f\\n",',
 ' oplsda_perm$observed_ratio, oplsda_perm$p_value))',
 '',
 '# ----7a. OPLSDA Score Plot ----',
 'p_oplsda <- ggplot(oplsda_out, aes(',
 ' x = predictive,',
 ' y = orthogonal1,',
 ' color = group, shape = group',
 ')) +',
 ' geom_point(size =4, alpha =0.85) +',
 ' stat_ellipse(level =0.95, type = "norm", size =1, alpha =0.5) +',
 ' scale_color_manual(values = group_colors) +',
 ' scale_shape_manual(values = group_shapes) +',
 ' geom_text_repel(aes(label = sample), size =3, max.overlaps =15, show.legend = FALSE) +',
 ' labs(',
 ' x = sprintf("Predictive Component (%.1f%%)", oplsda_var[1]),',
 ' y = sprintf("Orthogonal Component1 (%.1f%%)", oplsda_var[2]),',
 ' title = "OPLSDA Score Plot",',
 ' color = "Group", shape = "Group"',
 ' ) +',
 ' theme_pub()',
 '',
 'ggsave(file.path(output_dir, "figures", "oplsda_score_plot.png"),',
 ' p_oplsda, width =8, height =6, dpi =300)',
 'ggsave(file.path(output_dir, "figures", "oplsda_score_plot.pdf"),',
 ' p_oplsda, width =8, height =6)',
 'cat(" -> oplsda_score_plot saved\\n")',
 '',
 '# ----7b. OPLSDA S-plot ----',
 'cat(">>> Generating OPLSDA S-plot...\\n")',
 'tryCatch({',
 ' if (inherits(oplsda_model, "opls")) {',
 ' p_loadings <- oplsda_model@loadingMN[,1]',
 ' pred_score <- oplsda_score_matrix[,1]',
 ' X_mat_used <- t(expr_matrix)',
 ' } else {',
 ' p_loadings <- oplsda_model$loadings$X[,1]',
 ' if (is.null(p_loadings)) p_loadings <- oplsda_model$loadings.star$X[,1]',
 ' pred_score <- oplsda_scores$predictive',
 ' X_mat_used <- t(expr_matrix)',
 ' }',
 ' p_corr <- apply(X_mat_used,2, function(x) cor(x, pred_score, use = "pairwise"))',
 ' splot_df <- data.frame(',
 ' molecule = names(p_loadings),',
 ' loading = as.numeric(p_loadings),',
 ' p_corr = as.numeric(p_corr),',
 ' VIP = oplsda_vip_df$VIP[match(names(p_loadings), oplsda_vip_df$molecule)],',
 ' stringsAsFactors = FALSE',
 ' )',
 ' splot_df$significance <- ifelse(',
 ' abs(splot_df$p_corr) >0.5 & splot_df$VIP >1, "High",',
 ' ifelse(abs(splot_df$p_corr) >0.3 & splot_df$VIP >0.8, "Medium", "Low")',
 ' )',
 ' top_sig <- splot_df[order(-abs(splot_df$p_corr)), ]',
 ' top_sig <- top_sig[top_sig$significance == "High", ]',
 ' top_labels <- head(top_sig$molecule,15)',
 ' splot_df$label <- ifelse(splot_df$molecule %in% top_labels, splot_df$molecule, "")',
 ' p_splot <- ggplot(splot_df, aes(x = loading, y = p_corr, color = significance)) +',
 ' geom_point(alpha =0.5, size =1.5) +',
 ' scale_color_manual(',
 ' values = c("High" = "#D73027", "Medium" = "#FDAE61", "Low" = "#ABD9E9")',
 ' ) +',
 ' geom_text_repel(aes(label = label), size =2.5, max.overlaps =20, box.padding =0.3) +',
 ' geom_hline(yintercept = c(-0.5,0.5), linetype = "dashed", color = "grey50", alpha =0.5) +',
 ' geom_vline(xintercept =0, linetype = "dotted", color = "grey50") +',
 ' labs(x = "Loading (p[1])", y = "Correlation p(corr)[1]",',
 ' title = "OPLSDA S-plot", color = "Significance") +',
 ' theme_pub()',
 ' ggsave(file.path(output_dir, "figures", "oplsda_splot.png"),',
 ' p_splot, width =10, height =8, dpi =300)',
 ' ggsave(file.path(output_dir, "figures", "oplsda_splot.pdf"),',
 ' p_splot, width =10, height =8)',
 ' cat(" -> oplsda_splot saved\\n")',
 '}, error = function(e) {',
 ' cat(" Warning: S-plot failed:", e$message, "\\n")',
 '})'
)

# Replace the section
lines <- c(lines[1:(start_line-1)], new_oplsda_section, lines[(end_line):length(lines)])

writeLines(lines, file_path)
cat("OPLSDA section replaced. Lines", start_line, "to", end_line, "replaced.\n")
