Imports Microsoft.VisualBasic.Serialization.JSON
Imports Ollama
Imports OmicsAgent.AppRuntime

' ============================================================================
' 模块 10: 整理结果文件（生成 xlsx 表格）
' ============================================================================

''' <summary>
''' 结果表格整理模块。
'''
''' 遍历 _context.ModuleResults 列表中每个已完成模块的分析结果，
''' 针对每个模块独立生成一个 xlsx 文件：
''' 1. 在 VB.NET 中通过 For 循环遍历 _context.ModuleResults 每一个模块；
''' 2. 列举当前循环模块中位于 ModuleResult.Workdir 下的 csv 表格文件；
''' 3. 提示 LLM 结合当前模块的 ModuleResult.Goal、ModuleResult.Conclusion 与 kb.json
'''    知识库内容，为每张 sheet 第一行编写英文注释（讲解分析结果内容 + 每一列含义）；
''' 4. 提示 LLM 编写基于 openxlsx 的 R 脚本，按规定的样式读取 CSV 并生成 xlsx 结果文件；
''' 5. 由 ShellTool 执行该 R 脚本，所生成的 xlsx 保存到当前循环模块的 OutputDir。
'''
''' xlsx 表格样式要求（写入 LLM 提示词）：
''' - 全局采用 Cambria Math 11 号字体
''' - 表格缩放 90%
''' - 背景色为默认的白色
''' - 第一列（id 列）：浅灰色背景色，斜体，黑色字体颜色
''' - 第一行（注释说明文本行）：默认背景色，草绿色字体颜色
''' - 第二行（列标题行）：深蓝色背景色，白色字体颜色，加粗字体
''' - 第一列 + 第二行进行 freeze panes 冻结
''' - 所有文本信息（文件名、注释、标题、列标题）均为英文
''' </summary>
Public Class ResultTablesModule : Inherits AnalysisModuleBase

    Public Overrides ReadOnly Property ModuleName As String = "Result Tables Compilation"
    Public Overrides ReadOnly Property ModuleIndex As Integer = 10

    Public Overrides ReadOnly Property CsvFileNamePrefix As String
        Get
            Return "result_tables_"
        End Get
    End Property

    Public Sub New(config As AgentConfig, context As AnalysisContext, Optional logger As Action(Of String) = Nothing)
        MyBase.New(config, context, logger)
    End Sub

    Protected Overrides Function GeneratePlanPromptText() As String
        Return "Design a plan to compile intermediate CSV result tables into organized XLSX files, one XLSX per analysis module.
1. Iterate over _context.ModuleResults (the list of completed analysis modules)
2. For each ModuleResult, recursively list all CSV files located in ModuleResult.Workdir
3. Skip modules that produced no CSV files
4. For each module, generate a single XLSX file with one sheet per CSV:
   - Row 1: Description/annotation text (forest green font), in English
   - Row 2: Column headers (dark blue background, white bold font)
   - Row 3+: Data
   - First column: light gray background, italic, black font
   - Freeze panes at B3
5. The annotation text for row 1 of each sheet must be generated by the LLM using the current module's Goal, Conclusion and the kb.json knowledge base content
6. The actual XLSX files will be generated by an R script (openxlsx) written by the LLM, saved to the current module's ModuleResult.OutputDir"
    End Function

    Protected Overrides Function GetConclusionItems() As String
        Return "1. 结果表格整理的整体情况（遍历的模块数量、生成的 XLSX 文件数量、包含的工作表数量）
2. 每个分析模块的结果 xlsx 文件汇总情况（保存于各模块 OutputDir）
3. 表格样式规范的应用情况（字体、背景色、冻结窗格等）
4. 各工作表的英文注释说明内容（结合模块目标/结论与知识库）
5. 与用户研究主题的关联性说明"
    End Function

    ''' <summary>
    ''' 调用 LLM 编写并执行脚本。
    ''' 通过 For 循环遍历 _context.ModuleResults 中每个已完成模块，
    ''' 为每个模块独立生成注释 JSON 与 xlsx 文件。
    ''' </summary>
    Protected Overrides Async Function GenerateAndRunScriptAsync(llm As LLMClient, plan As ModulePlan, [step] As [Step], cancellationToken As CancellationToken) As Task
        LogInfo("Compiling result tables into XLSX files via LLM-generated R script (per-module iteration)...")

        If _context.ModuleResults.IsNullOrEmpty Then
            LogInfo("No module results available. Skipping XLSX generation.")
            Return
        End If

        ' 在循环外一次性读取 kb.json 知识库内容，复用于每个模块的注释提示词
        Dim kbContent = ReadKnowledgeBaseContent()

        ' 遍历每个已完成模块的分析结果
        For Each mr As ModuleResult In _context.ModuleResults
            If cancellationToken.IsCancellationRequested Then Exit For

            Try
                Await ProcessModuleAsync(mr, kbContent, plan, [step], cancellationToken)
            Catch ex As Exception
                LogInfo($"[警告] 模块 {mr.ModuleIndex} ({mr.ModuleName}) 的 xlsx 生成失败：{ex.Message}")
                LogInfo(ex.StackTrace)
                ' 单个模块失败不影响其他模块处理
                Continue For
            End Try
        Next
    End Function

    ''' <summary>处理单个模块：收集 CSV → 生成注释 → 生成并执行 R 脚本</summary>
    Private Async Function ProcessModuleAsync(mr As ModuleResult, kbContent As String, plan As ModulePlan, [step] As [Step], cancellationToken As CancellationToken) As Task
        ' 1. 列举当前模块 Workdir 下的所有 CSV 文件
        Dim csvFiles = CollectModuleCsvFiles(mr.Workdir)

        If csvFiles.Count = 0 Then
            LogInfo($"模块 {mr.ModuleIndex} ({mr.ModuleName}) 在 Workdir 中未发现 CSV 文件，跳过：{mr.Workdir}")
            Return
        End If

        LogInfo($"正在处理模块 {mr.ModuleIndex} ({mr.ModuleName})：发现 {csvFiles.Count} 个 CSV 文件")

        ' 确保输出目录存在
        If Not String.IsNullOrEmpty(mr.OutputDir) Then
            Call mr.OutputDir.MakeDir
        Else
            LogInfo($"模块 {mr.ModuleIndex} ({mr.ModuleName}) 的 OutputDir 为空，跳过。")
            Return
        End If

        Dim xlsxFileName = GetModuleXlsxFileName(mr)

        ' 2. 第一次 LLM 调用：生成该模块每张 sheet 第一行的英文注释说明，保存为 JSON
        Dim descJson = Await GenerateAnnotationsForModuleAsync(mr, csvFiles, kbContent, cancellationToken)
        Dim descPath = Path.Combine(mr.OutputDir, "table_descriptions.json")
        Call descJson.SaveTo(descPath)
        LogInfo($"模块 {mr.ModuleIndex} 注释 JSON 已保存：{descPath}")

        ' 3. 第二次 LLM 调用：通过函数调用工具编写并执行生成 xlsx 的 R 脚本
        Dim prompt = BuildRScriptPrompt(descPath, mr.OutputDir, xlsxFileName, mr, plan, [step])

        Using llmRscript As LLMClient = _config.CreateLLMClient(FolderBaseName & "-xlsx_" & mr.ModuleIndex, _context.TmpDir)
            Call RegisterTools(llmRscript, True)
            Await llmRscript.Chat(prompt, cancellationToken)
        End Using

        LogInfo($"模块 {mr.ModuleIndex} ({mr.ModuleName}) 的 xlsx 已生成：{Path.Combine(mr.OutputDir, xlsxFileName)}")
    End Function

    ''' <summary>递归收集指定 Workdir 下的所有 CSV 文件</summary>
    Private Function CollectModuleCsvFiles(workdir As String) As List(Of String)
        Dim result As New List(Of String)()

        If String.IsNullOrEmpty(workdir) OrElse Not Directory.Exists(workdir) Then
            Return result
        End If

        Try
            result.AddRange(Directory.GetFiles(workdir, "*.csv", SearchOption.AllDirectories))
        Catch ex As Exception
            LogInfo($"[警告] 扫描 Workdir 失败 ({workdir})：{ex.Message}")
        End Try

        Return result
    End Function

    ''' <summary>
    ''' 读取 kb.json 知识库内容并截断至 30000 字符，返回字符串。
    ''' 在循环外调用一次，复用于每个模块的注释提示词。
    ''' </summary>
    Private Function ReadKnowledgeBaseContent() As String
        If File.Exists(_context.KnowledgeBaseFile) Then
            Try
                Dim kb = File.ReadAllText(_context.KnowledgeBaseFile, Encoding.UTF8)
                Dim stripLen As Integer = 30000
                If kb.Length > stripLen Then
                    Return kb.Substring(0, stripLen) & "...[truncated]"
                Else
                    Return kb
                End If
            Catch ex As Exception
                LogInfo($"[警告] 读取 kb.json 失败：{ex.Message}")
            End Try
        End If

        Return "(No knowledge base file available)"
    End Function

    ''' <summary>
    ''' 根据模块索引与名称生成 xlsx 文件名，格式为 {ModuleIndex}_{normalize(ModuleName)}.xlsx
    ''' </summary>
    Private Function GetModuleXlsxFileName(mr As ModuleResult) As String
        Dim safeName = mr.ModuleName.NormalizePathString(alphabetOnly:=True).Replace(" ", "_").ToLower()
        Return $"{mr.ModuleIndex}_{safeName}.xlsx"
    End Function

    ''' <summary>读取 CSV 文件的第一行表头</summary>
    Private Function GetCsvHeader(csvPath As String) As List(Of String)
        Dim result As New List(Of String)()
        Try
            Dim firstLine = File.ReadLines(csvPath).FirstOrDefault()
            If Not String.IsNullOrEmpty(firstLine) Then
                result.AddRange(firstLine.Split(","c))
            End If
        Catch
        End Try
        Return result
    End Function

    ''' <summary>清洗工作表名称，符合 Excel 限制（&lt;=31 字符，无非法字符）</summary>
    Private Function SanitizeSheetName(name As String) As String
        Dim s = Path.GetFileNameWithoutExtension(name)
        If s.Length > 31 Then s = s.Substring(0, 31)
        s = s.Replace(":"c, "_"c).Replace("\"c, "_"c).Replace("/"c, "_"c).Replace("?"c, "_"c).Replace("*"c, "_"c).Replace("["c, "_"c).Replace("]"c, "_"c)
        Return s
    End Function

    ''' <summary>
    ''' 第一次 LLM 调用：结合当前模块的 Goal、Conclusion 与 kb.json 知识库内容，
    ''' 为该模块每张 sheet 第一行生成英文注释（讲解分析结果内容 + 每一列含义），
    ''' 并保存为结构化 JSON。
    ''' </summary>
    Private Async Function GenerateAnnotationsForModuleAsync(mr As ModuleResult, csvFiles As List(Of String), kbContent As String, cancellationToken As CancellationToken) As Task(Of String)
        ' 构建单模块骨架 JSON（含 csv 绝对路径、英文 sheet 名、空注释）
        Dim sk As New StringBuilder()
        sk.AppendLine("{")
        sk.AppendLine($"  ""module_index"": {mr.ModuleIndex},")
        sk.AppendLine($"  ""module_name"": ""{mr.ModuleName}"",")
        sk.AppendLine($"  ""xlsx_file"": ""{GetModuleXlsxFileName(mr)}"",")
        sk.AppendLine($"  ""output_dir"": ""{mr.OutputDir}"",")
        sk.AppendLine("  ""sheets"": [")
        Dim firstSheet = True
        For Each csv In csvFiles
            If Not firstSheet Then sk.AppendLine("    },")
            firstSheet = False
            sk.AppendLine("    {")
            sk.AppendLine($"      ""csv"": ""{csv}"",")
            sk.AppendLine($"      ""sheet_name"": ""{SanitizeSheetName(csv)}"",")
            sk.AppendLine("      ""annotation"": """"")
        Next
        If csvFiles.Count > 0 Then sk.AppendLine("    }")
        sk.AppendLine("  ]")
        sk.AppendLine("}")

        Dim skeleton = sk.ToString()

        ' 构建每个 sheet 的表头信息，供 LLM 编写注释
        Dim headersInfo As New StringBuilder()
        headersInfo.AppendLine($"## Module {mr.ModuleIndex}: {mr.ModuleName}")
        For Each csv In csvFiles
            Dim hdr = GetCsvHeader(csv)
            headersInfo.AppendLine($"- CSV: {Path.GetFileName(csv)} ({csv})")
            headersInfo.AppendLine($"  Sheet name: {SanitizeSheetName(csv)}")
            headersInfo.AppendLine($"  Columns ({hdr.Count}): {String.Join(", ", hdr)}")
        Next

        Using llm As LLMClient = _config.CreateLLMClient(FolderBaseName & "-sheet_comment_" & mr.ModuleIndex, _context.TmpDir)
            Call RegisterTools(llm, True)

            Dim prompt As String = <root><![CDATA[
You are a bioinformatics data analyst. Your task is to write English annotation text for the FIRST ROW of each sheet in a result XLSX file that compiles the CSV result tables produced by ONE analysis module.

# Module Information
- Module index: {MODULE_INDEX}
- Module name: {MODULE_NAME}
- Module analysis goal: {MODULE_GOAL}

# Module Stage Conclusion (analysis findings)
{MODULE_CONCLUSION}

# Knowledge Base (kb.json)
{KB_CONTENT}

# CSV files produced by this module (each becomes a sheet)
{HEADERS}

# Table descriptions skeleton (JSON)
The following JSON lists the CSV files (sheets) to include in this module's XLSX file. The 'annotation' fields are currently EMPTY.

{SKELETON}

# Your Task
For EACH sheet, fill in the 'annotation' field (a string) with a clear English description that will be placed in the FIRST ROW of that sheet. The annotation must:
- Explain what data / contents this table contains.
- Explain the meaning of EACH column (use the column list provided above for that CSV).
- Connect the table contents to this module's goal and conclusion, and to relevant biological knowledge from the knowledge base (e.g., key genes/pathways/mechanisms) when applicable.
- Explain what biological knowledge / insights a user can gain from this table.
Keep it informative but concise (typically 2-5 sentences). You MAY also refine 'sheet_name' to a clearer English name (<=31 chars, without : \ / ? * [ ] characters), but you MUST keep the 'csv' absolute path EXACTLY as given.

Return ONLY the completed JSON (no extra explanation, no markdown code fences).
]]></root>.Value

            prompt = prompt.Replace("{MODULE_INDEX}", mr.ModuleIndex.ToString()) _
                           .Replace("{MODULE_NAME}", mr.ModuleName) _
                           .Replace("{MODULE_GOAL}", If(mr.Goal, "(not provided)")) _
                           .Replace("{MODULE_CONCLUSION}", If(mr.Conclusion, "(not provided)")) _
                           .Replace("{KB_CONTENT}", kbContent) _
                           .Replace("{HEADERS}", headersInfo.ToString()) _
                           .Replace("{SKELETON}", skeleton)

            Dim resp = Await llm.Chat(prompt, cancellationToken)
            Dim json = resp.ExtractJsonFromResponse
            If Not String.IsNullOrEmpty(json) Then
                Return json
            End If
        End Using

        ' LLM 调用失败时回退到骨架（注释为空），保证 R 脚本仍可运行
        Return skeleton
    End Function

    ''' <summary>
    ''' 构建第二次 LLM 调用的提示词：要求 LLM 编写基于 openxlsx 的 R 脚本，
    ''' 按规定的样式读取 CSV 与注释 JSON，生成单个 xlsx 结果文件并保存到模块 OutputDir。
    ''' </summary>
    Private Function BuildRScriptPrompt(descPath As String, outputDir As String, xlsxFileName As String, mr As ModuleResult, plan As ModulePlan, [step] As [Step]) As String
        Dim prompt As String = <root><![CDATA[
You are a bioinformatics R scripting expert. Write a complete R script that compiles the CSV result tables of ONE analysis module into a single organized, styled XLSX file using the openxlsx package.

# Inputs
- A JSON file at: {DESC_PATH}
  describes the module's XLSX file to create, the CSV files (sheets) it contains, and an English annotation text for the first row of each sheet.
- Output directory for the XLSX file: {OUT_DIR}
- XLSX file name: {XLSX_FILE}

# Plan Execution Context
- Module: Result Tables Compilation (processing module {MODULE_INDEX}: {MODULE_NAME})
- Plan goal: {PLAN_GOAL}
- Current execution step: {STEP}
- All scripts and the generated files are placed in this designated temporary workspace folder: {WORKSPACE}

# JSON structure (table_descriptions.json)
{
  'module_index': <integer>,
  'module_name': '<module name>',
  'xlsx_file': '<xlsx file name>',
  'output_dir': '<absolute output dir path>',
  'sheets': [
    { 'csv': '<absolute csv path>', 'sheet_name': '<english sheet name>', 'annotation': '<english annotation text for row 1>' }
  ]
}

# Your Task
Write an R script that:
1. Ensures the openxlsx package is available (use: if (!require(openxlsx)) install.packages('openxlsx'); library(openxlsx)). Also ensure jsonlite is available the same way.
2. Reads the JSON with jsonlite::fromJSON('{DESC_PATH}', simplifyVector = TRUE).
3. Create a new workbook: wb <- createWorkbook()
4. For each sheet entry in desc$sheets:
   a. Read the CSV: df <- read.csv(sh$csv, stringsAsFactors = FALSE, check.names = FALSE)
   b. Add a worksheet with a valid English sheet name (<=31 chars, no : \ / ? * [ ] characters): addWorksheet(wb, sheetName = sh$sheet_name)
   c. Write the annotation text into cell A1 (row 1): writeData(wb, sh$sheet_name, x = sh$annotation, startRow = 1, startCol = 1, colNames = FALSE, rowNames = FALSE)
   d. Write the CSV column headers into row 2: writeData(wb, sh$sheet_name, x = as.data.frame(t(colnames(df))), startRow = 2, startCol = 1, colNames = FALSE, rowNames = FALSE)
   e. Write the CSV data (without its header) starting at row 3, column 1: writeData(wb, sh$sheet_name, x = df, startRow = 3, startCol = 1, colNames = FALSE, rowNames = FALSE)
5. Define and apply the following styles (ALL using font name 'Cambria Math', size 11):
   - defaultStyle: Cambria Math 11, default white background. Apply to the whole used range first.
   - annotStyle: default background, forest green font color '#228B22'. Apply to row 1 (all used columns).
   - headerStyle: dark blue background '#1F4E79', white font '#FFFFFF', bold textDecoration = 'bold'. Apply to row 2 (all used columns).
   - idStyle: light gray background '#D9D9D9', italic textDecoration = 'italic', black font '#000000'. Apply to the first column (column A), rows 3 to last data row.
   Apply defaultStyle first, then overlay annotStyle / headerStyle / idStyle so specific styles win.
6. Freeze the first column AND the first two rows (TopLeft cell = B3). In openxlsx: freezePane(wb, sh$sheet_name, firstRow = 3, firstCol = 2)
7. Set sheet zoom to 90%: setZoom(wb, sh$sheet_name, zoom = 90)
8. Save the workbook: saveWorkbook(wb, file.path('{OUT_DIR}', '{XLSX_FILE}'), overwrite = TRUE)
9. Print progress messages and handle missing files gracefully (skip and warn, do not stop).
10. IMPORTANT: All text (XLSX file names, sheet names, annotations, column headers) MUST be in English.

# Reference template (adapt as needed)
library(openxlsx)
if (!require(openxlsx)) install.packages('openxlsx')
if (!require(jsonlite)) install.packages('jsonlite')
library(openxlsx)
library(jsonlite)

desc <- fromJSON('{DESC_PATH}', simplifyVector = TRUE)
out_dir <- '{OUT_DIR}'
xlsx_name <- '{XLSX_FILE}'

defaultStyle <- createStyle(fontName = 'Cambria Math', fontSize = 11)
annotStyle <- createStyle(fontName = 'Cambria Math', fontSize = 11, fontColour = '#228B22')
headerStyle <- createStyle(fontName = 'Cambria Math', fontSize = 11, fontColour = 'FFFFFF', fgFill = '#1F4E79', textDecoration = 'bold')
idStyle <- createStyle(fontName = 'Cambria Math', fontSize = 11, fgFill = '#D9D9D9', textDecoration = 'italic', fontColour = '000000')

wb <- createWorkbook()
for (j in seq_along(desc$sheets)) {
  sh <- desc$sheets[[j]]
  if (!file.exists(sh$csv)) { warning(paste('Missing CSV:', sh$csv)); next }
  df <- read.csv(sh$csv, stringsAsFactors = FALSE, check.names = FALSE)
  ncol <- ncol(df)
  lastRow <- nrow(df) + 2
  addWorksheet(wb, sheetName = sh$sheet_name)
  writeData(wb, sh$sheet_name, x = sh$annotation, startRow = 1, startCol = 1, colNames = FALSE, rowNames = FALSE)
  writeData(wb, sh$sheet_name, x = as.data.frame(t(colnames(df))), startRow = 2, startCol = 1, colNames = FALSE, rowNames = FALSE)
  writeData(wb, sh$sheet_name, x = df, startRow = 3, startCol = 1, colNames = FALSE, rowNames = FALSE)
  addStyle(wb, sh$sheet_name, defaultStyle, rows = 1:lastRow, cols = 1:ncol, gridExpand = TRUE)
  addStyle(wb, sh$sheet_name, annotStyle, rows = 1, cols = 1:ncol, gridExpand = TRUE)
  addStyle(wb, sh$sheet_name, headerStyle, rows = 2, cols = 1:ncol, gridExpand = TRUE)
  addStyle(wb, sh$sheet_name, idStyle, rows = 3:lastRow, cols = 1, gridExpand = TRUE)
  freezePane(wb, sh$sheet_name, firstRow = 3, firstCol = 2)
  setZoom(wb, sh$sheet_name, zoom = 90)
  cat(paste('Prepared sheet', sh$sheet_name, 'for', xlsx_name, '\n'))
}
saveWorkbook(wb, file.path(out_dir, xlsx_name), overwrite = TRUE)
cat(paste('Saved', xlsx_name, '\n'))

# Important Notes
- Use absolute paths.
- Make sure numeric columns remain numeric (do not wrap them as text).
- The script must run end-to-end without further input.

# Execution Instructions
- Write the R script to a file in the workspace using the write_file tool (e.g., 'module_10_result_tables_{MODULE_INDEX}.R')
- Execute the R script using the run_rscript tool
- Verify the XLSX file is generated successfully in the output directory
]]></root>.Value

        prompt = prompt.Replace("{DESC_PATH}", descPath) _
                       .Replace("{OUT_DIR}", outputDir) _
                       .Replace("{XLSX_FILE}", xlsxFileName) _
                       .Replace("{MODULE_INDEX}", mr.ModuleIndex.ToString()) _
                       .Replace("{MODULE_NAME}", mr.ModuleName) _
                       .Replace("{PLAN_GOAL}", plan.goal) _
                       .Replace("{STEP}", [step].GetJson) _
                       .Replace("{WORKSPACE}", Workspace.GetDirectoryFullPath)
        Return prompt
    End Function
End Class
