// *****************************************************************************
// * This is an automatically generated header file for UI Element definition  *
// * resource symbols and values. Please do not modify manually.               *
// *****************************************************************************

#pragma once

#define cmdButtonLLMTool 25 
#define cmdButtonLLMTool_LabelTitle_RESID 60001
#define cmdButtonLLMTool_SmallImages_192__RESID 60002
#define cmdButtonLLMTool_LargeImages_192__RESID 60003
#define cmdBtnOpenKBLib 10 
#define cmdBtnOpenKBLib_LabelTitle_RESID 60004
#define cmdBtnOpenKBLib_SmallImages_192__RESID 60005
#define cmdBtnOpenKBLib_LargeImages_192__RESID 60006
#define cmdButtonExit 17 
#define cmdButtonExit_LabelTitle_RESID 60007
#define cmdButtonExit_SmallImages_192__RESID 60008
#define cmdButtonExit_LargeImages_192__RESID 60009
#define cmdButtonLicense 18 
#define cmdButtonLicense_LabelTitle_RESID 60010
#define cmdButtonLicense_SmallImages_192__RESID 60011
#define cmdButtonLicense_LargeImages_192__RESID 60012
#define cmdButtonOpenConsole 22 
#define cmdButtonOpenConsole_LabelTitle_RESID 60013
#define cmdButtonOpenConsole_SmallImages_192__RESID 60014
#define cmdButtonOpenConsole_LargeImages_192__RESID 60015
#define cmdButtonOpenFolder 16 
#define cmdButtonOpenFolder_LabelTitle_RESID 60016
#define cmdButtonOpenFolder_SmallImages_192__RESID 60017
#define cmdButtonOpenFolder_LargeImages_192__RESID 60018
#define cmdButtonOpenKb 2 
#define cmdButtonOpenKb_LabelTitle_RESID 60019
#define cmdButtonOpenKb_SmallImages_192__RESID 60020
#define cmdButtonOpenKb_LargeImages_192__RESID 60021
#define cmdButtonOpenResearch 6 
#define cmdButtonOpenResearch_LabelTitle_RESID 60022
#define cmdButtonOpenResearch_SmallImages_192__RESID 60023
#define cmdButtonOpenResearch_LargeImages_192__RESID 60024
#define cmdButtonToggleTheme 15 
#define cmdButtonToggleTheme_LabelTitle_RESID 60025
#define cmdButtonToggleTheme_SmallImages_192__RESID 60026
#define cmdButtonToggleTheme_LargeImages_192__RESID 60027
#define cmdButtonVennTool 23 
#define cmdButtonVennTool_LabelTitle_RESID 60028
#define cmdButtonVennTool_SmallImages_192__RESID 60029
#define cmdButtonVennTool_LargeImages_192__RESID 60030
#define cmdGroupInformation 20 
#define cmdGroupInformation_LabelTitle_RESID 60031
#define cmdGroupKBLib 13 
#define cmdGroupKBLib_LabelTitle_RESID 60032
#define cmdGroupMain 7 
#define cmdGroupMain_LabelTitle_RESID 60033
#define cmdGroupResearchWork 4 
#define cmdGroupResearchWork_LabelTitle_RESID 60034
#define cmdGroupTools 14 
#define cmdGroupTools_LabelTitle_RESID 60035
#define cmdGroupWorkTools 21 
#define cmdGroupWorkTools_LabelTitle_RESID 60036
#define cmdMenuKBLib 12 
#define cmdMenuKBLib_LabelTitle_RESID 60037
#define cmdMenuResearchWork 3 
#define cmdMenuResearchWork_LabelTitle_RESID 60038
#define cmdMenuTools 24 
#define cmdMenuTools_LabelTitle_RESID 60039
#define cmdPanelMain 8 
#define cmdPanelMain_LabelTitle_RESID 60040
#define cmdTabInformation 19 
#define cmdTabInformation_LabelTitle_RESID 60041
#define cmdTabKBLib 11 
#define cmdTabKBLib_LabelTitle_RESID 60042
#define cmdTabMain 9 
#define cmdTabMain_LabelTitle_RESID 60043
#define cmdTabResearchWork 5 
#define cmdTabResearchWork_LabelTitle_RESID 60044
#define cmdButtonDataset 26 
#define cmdButtonDataset_LabelTitle_RESID 60045
#define cmdButtonDataset_SmallImages_192__RESID 60046
#define cmdButtonDataset_LargeImages_192__RESID 60047
#define InternalCmd2_LabelTitle_RESID 60048
