//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using RibbonLib;
using RibbonLib.Controls;

namespace RibbonLib.Controls
{
    partial class RibbonItems
    {
        private static class Cmd
        {
            public const uint cmdButtonOpenFolder = 16;
            public const uint cmdButtonOpenResearch = 6;
            public const uint cmdMenuTools = 24;
            public const uint cmdButtonOpenConsole = 22;
            public const uint cmdButtonVennTool = 23;
            public const uint cmdButtonLLMTool = 25;
            public const uint cmdButtonSettings = 38;
            public const uint cmdButtonLicense = 18;
            public const uint cmdButtonExit = 17;
            public const uint cmdMenuResearchWork = 3;
            public const uint cmdTabResearchWork = 5;
            public const uint cmdGroupResearchWork = 4;
            public const uint cmdButtonOpenKb = 2;
            public const uint cmdButtonDataset = 26;
            public const uint cmdButtonEditResearchTopic = 42;
            public const uint cmdGroupResearchAgentWork = 27;
            public const uint cmdButtonStart = 28;
            public const uint cmdButtonRefreshProgress = 44;
            public const uint cmdMenuKBLib = 12;
            public const uint cmdTabKBLib = 11;
            public const uint cmdGroupKBLib = 13;
            public const uint cmdButtonOpenKBFolder = 43;
            public const uint cmdBtnOpenKBLib = 10;
            public const uint cmdButtonUpdateKB = 45;
            public const uint cmdGroupTools = 14;
            public const uint cmdButtonToggleTheme = 15;
            public const uint cmdMenuDataSet = 29;
            public const uint cmdTabDataSet = 30;
            public const uint cmdGroupDataSet = 31;
            public const uint cmdButtonLoadDataSet = 32;
            public const uint cmdButtonSaveDataSet = 33;
            public const uint cmdButtonSaveAsDataSet = 34;
            public const uint cmdButtonDataSetToggleOmics = 37;
            public const uint cmdButtonPreviewDataset = 35;
            public const uint cmdButtonDataSetEditorToggleTheme = 36;
            public const uint cmdTabMain = 9;
            public const uint cmdGroupMain = 7;
            public const uint cmdGroupWorkTools = 21;
            public const uint cmdGroupWorkbench = 40;
            public const uint cmdButtonStartPage = 39;
            public const uint cmdButtonOpenOutput = 41;
            public const uint cmdTabInformation = 19;
            public const uint cmdGroupInformation = 20;
        }

        // ContextPopup CommandName

        public Ribbon Ribbon { get; private set; }
        public RibbonButton ButtonOpenFolder { get; private set; }
        public RibbonButton ButtonOpenResearch { get; private set; }
        public RibbonDropDownButton MenuTools { get; private set; }
        public RibbonButton ButtonOpenConsole { get; private set; }
        public RibbonButton ButtonVennTool { get; private set; }
        public RibbonButton ButtonLLMTool { get; private set; }
        public RibbonButton ButtonSettings { get; private set; }
        public RibbonButton ButtonLicense { get; private set; }
        public RibbonButton ButtonExit { get; private set; }
        public RibbonTabGroup MenuResearchWork { get; private set; }
        public RibbonTab TabResearchWork { get; private set; }
        public RibbonGroup GroupResearchWork { get; private set; }
        public RibbonButton ButtonOpenKb { get; private set; }
        public RibbonButton ButtonDataset { get; private set; }
        public RibbonButton ButtonEditResearchTopic { get; private set; }
        public RibbonGroup GroupResearchAgentWork { get; private set; }
        public RibbonButton ButtonStart { get; private set; }
        public RibbonButton ButtonRefreshProgress { get; private set; }
        public RibbonTabGroup MenuKBLib { get; private set; }
        public RibbonTab TabKBLib { get; private set; }
        public RibbonGroup GroupKBLib { get; private set; }
        public RibbonButton ButtonOpenKBFolder { get; private set; }
        public RibbonButton BtnOpenKBLib { get; private set; }
        public RibbonButton ButtonUpdateKB { get; private set; }
        public RibbonGroup GroupTools { get; private set; }
        public RibbonButton ButtonToggleTheme { get; private set; }
        public RibbonTabGroup MenuDataSet { get; private set; }
        public RibbonTab TabDataSet { get; private set; }
        public RibbonGroup GroupDataSet { get; private set; }
        public RibbonButton ButtonLoadDataSet { get; private set; }
        public RibbonButton ButtonSaveDataSet { get; private set; }
        public RibbonButton ButtonSaveAsDataSet { get; private set; }
        public RibbonButton ButtonDataSetToggleOmics { get; private set; }
        public RibbonButton ButtonPreviewDataset { get; private set; }
        public RibbonButton ButtonDataSetEditorToggleTheme { get; private set; }
        public RibbonTab TabMain { get; private set; }
        public RibbonGroup GroupMain { get; private set; }
        public RibbonGroup GroupWorkTools { get; private set; }
        public RibbonGroup GroupWorkbench { get; private set; }
        public RibbonButton ButtonStartPage { get; private set; }
        public RibbonButton ButtonOpenOutput { get; private set; }
        public RibbonTab TabInformation { get; private set; }
        public RibbonGroup GroupInformation { get; private set; }

        public RibbonItems(Ribbon ribbon)
        {
            if (ribbon == null)
                throw new ArgumentNullException(nameof(ribbon), "Parameter is null");
            this.Ribbon = ribbon;
            ButtonOpenFolder = new RibbonButton(ribbon, Cmd.cmdButtonOpenFolder);
            ButtonOpenResearch = new RibbonButton(ribbon, Cmd.cmdButtonOpenResearch);
            MenuTools = new RibbonDropDownButton(ribbon, Cmd.cmdMenuTools);
            ButtonOpenConsole = new RibbonButton(ribbon, Cmd.cmdButtonOpenConsole);
            ButtonVennTool = new RibbonButton(ribbon, Cmd.cmdButtonVennTool);
            ButtonLLMTool = new RibbonButton(ribbon, Cmd.cmdButtonLLMTool);
            ButtonSettings = new RibbonButton(ribbon, Cmd.cmdButtonSettings);
            ButtonLicense = new RibbonButton(ribbon, Cmd.cmdButtonLicense);
            ButtonExit = new RibbonButton(ribbon, Cmd.cmdButtonExit);
            MenuResearchWork = new RibbonTabGroup(ribbon, Cmd.cmdMenuResearchWork);
            TabResearchWork = new RibbonTab(ribbon, Cmd.cmdTabResearchWork);
            GroupResearchWork = new RibbonGroup(ribbon, Cmd.cmdGroupResearchWork);
            ButtonOpenKb = new RibbonButton(ribbon, Cmd.cmdButtonOpenKb);
            ButtonDataset = new RibbonButton(ribbon, Cmd.cmdButtonDataset);
            ButtonEditResearchTopic = new RibbonButton(ribbon, Cmd.cmdButtonEditResearchTopic);
            GroupResearchAgentWork = new RibbonGroup(ribbon, Cmd.cmdGroupResearchAgentWork);
            ButtonStart = new RibbonButton(ribbon, Cmd.cmdButtonStart);
            ButtonRefreshProgress = new RibbonButton(ribbon, Cmd.cmdButtonRefreshProgress);
            MenuKBLib = new RibbonTabGroup(ribbon, Cmd.cmdMenuKBLib);
            TabKBLib = new RibbonTab(ribbon, Cmd.cmdTabKBLib);
            GroupKBLib = new RibbonGroup(ribbon, Cmd.cmdGroupKBLib);
            ButtonOpenKBFolder = new RibbonButton(ribbon, Cmd.cmdButtonOpenKBFolder);
            BtnOpenKBLib = new RibbonButton(ribbon, Cmd.cmdBtnOpenKBLib);
            ButtonUpdateKB = new RibbonButton(ribbon, Cmd.cmdButtonUpdateKB);
            GroupTools = new RibbonGroup(ribbon, Cmd.cmdGroupTools);
            ButtonToggleTheme = new RibbonButton(ribbon, Cmd.cmdButtonToggleTheme);
            MenuDataSet = new RibbonTabGroup(ribbon, Cmd.cmdMenuDataSet);
            TabDataSet = new RibbonTab(ribbon, Cmd.cmdTabDataSet);
            GroupDataSet = new RibbonGroup(ribbon, Cmd.cmdGroupDataSet);
            ButtonLoadDataSet = new RibbonButton(ribbon, Cmd.cmdButtonLoadDataSet);
            ButtonSaveDataSet = new RibbonButton(ribbon, Cmd.cmdButtonSaveDataSet);
            ButtonSaveAsDataSet = new RibbonButton(ribbon, Cmd.cmdButtonSaveAsDataSet);
            ButtonDataSetToggleOmics = new RibbonButton(ribbon, Cmd.cmdButtonDataSetToggleOmics);
            ButtonPreviewDataset = new RibbonButton(ribbon, Cmd.cmdButtonPreviewDataset);
            ButtonDataSetEditorToggleTheme = new RibbonButton(ribbon, Cmd.cmdButtonDataSetEditorToggleTheme);
            TabMain = new RibbonTab(ribbon, Cmd.cmdTabMain);
            GroupMain = new RibbonGroup(ribbon, Cmd.cmdGroupMain);
            GroupWorkTools = new RibbonGroup(ribbon, Cmd.cmdGroupWorkTools);
            GroupWorkbench = new RibbonGroup(ribbon, Cmd.cmdGroupWorkbench);
            ButtonStartPage = new RibbonButton(ribbon, Cmd.cmdButtonStartPage);
            ButtonOpenOutput = new RibbonButton(ribbon, Cmd.cmdButtonOpenOutput);
            TabInformation = new RibbonTab(ribbon, Cmd.cmdTabInformation);
            GroupInformation = new RibbonGroup(ribbon, Cmd.cmdGroupInformation);
        }

    }
}
