//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using RibbonLib;
using RibbonLib.Controls;

namespace RibbonLib.Controls
{
    partial class RibbonItems
    {
        private static class Cmd
        {
            public const uint cmdButtonOpenFolder = 16;
            public const uint cmdButtonOpenResearch = 6;
            public const uint cmdMenuTools = 24;
            public const uint cmdButtonOpenConsole = 22;
            public const uint cmdButtonVennTool = 23;
            public const uint cmdButtonLLMTool = 25;
            public const uint cmdButtonLicense = 18;
            public const uint cmdButtonExit = 17;
            public const uint cmdMenuResearchWork = 3;
            public const uint cmdTabResearchWork = 5;
            public const uint cmdGroupResearchWork = 4;
            public const uint cmdButtonOpenKb = 2;
            public const uint cmdMenuKBLib = 12;
            public const uint cmdTabKBLib = 11;
            public const uint cmdGroupKBLib = 13;
            public const uint cmdBtnOpenKBLib = 10;
            public const uint cmdGroupTools = 14;
            public const uint cmdButtonToggleTheme = 15;
            public const uint cmdTabMain = 9;
            public const uint cmdGroupMain = 7;
            public const uint cmdGroupWorkTools = 21;
            public const uint cmdTabInformation = 19;
            public const uint cmdGroupInformation = 20;
        }

        // ContextPopup CommandName

        public Ribbon Ribbon { get; private set; }
        public RibbonButton ButtonOpenFolder { get; private set; }
        public RibbonButton ButtonOpenResearch { get; private set; }
        public RibbonDropDownButton MenuTools { get; private set; }
        public RibbonButton ButtonOpenConsole { get; private set; }
        public RibbonButton ButtonVennTool { get; private set; }
        public RibbonButton ButtonLLMTool { get; private set; }
        public RibbonButton ButtonLicense { get; private set; }
        public RibbonButton ButtonExit { get; private set; }
        public RibbonTabGroup MenuResearchWork { get; private set; }
        public RibbonTab TabResearchWork { get; private set; }
        public RibbonGroup GroupResearchWork { get; private set; }
        public RibbonButton ButtonOpenKb { get; private set; }
        public RibbonTabGroup MenuKBLib { get; private set; }
        public RibbonTab TabKBLib { get; private set; }
        public RibbonGroup GroupKBLib { get; private set; }
        public RibbonButton BtnOpenKBLib { get; private set; }
        public RibbonGroup GroupTools { get; private set; }
        public RibbonButton ButtonToggleTheme { get; private set; }
        public RibbonTab TabMain { get; private set; }
        public RibbonGroup GroupMain { get; private set; }
        public RibbonGroup GroupWorkTools { get; private set; }
        public RibbonTab TabInformation { get; private set; }
        public RibbonGroup GroupInformation { get; private set; }

        public RibbonItems(Ribbon ribbon)
        {
            if (ribbon == null)
                throw new ArgumentNullException(nameof(ribbon), "Parameter is null");
            this.Ribbon = ribbon;
            ButtonOpenFolder = new RibbonButton(ribbon, Cmd.cmdButtonOpenFolder);
            ButtonOpenResearch = new RibbonButton(ribbon, Cmd.cmdButtonOpenResearch);
            MenuTools = new RibbonDropDownButton(ribbon, Cmd.cmdMenuTools);
            ButtonOpenConsole = new RibbonButton(ribbon, Cmd.cmdButtonOpenConsole);
            ButtonVennTool = new RibbonButton(ribbon, Cmd.cmdButtonVennTool);
            ButtonLLMTool = new RibbonButton(ribbon, Cmd.cmdButtonLLMTool);
            ButtonLicense = new RibbonButton(ribbon, Cmd.cmdButtonLicense);
            ButtonExit = new RibbonButton(ribbon, Cmd.cmdButtonExit);
            MenuResearchWork = new RibbonTabGroup(ribbon, Cmd.cmdMenuResearchWork);
            TabResearchWork = new RibbonTab(ribbon, Cmd.cmdTabResearchWork);
            GroupResearchWork = new RibbonGroup(ribbon, Cmd.cmdGroupResearchWork);
            ButtonOpenKb = new RibbonButton(ribbon, Cmd.cmdButtonOpenKb);
            MenuKBLib = new RibbonTabGroup(ribbon, Cmd.cmdMenuKBLib);
            TabKBLib = new RibbonTab(ribbon, Cmd.cmdTabKBLib);
            GroupKBLib = new RibbonGroup(ribbon, Cmd.cmdGroupKBLib);
            BtnOpenKBLib = new RibbonButton(ribbon, Cmd.cmdBtnOpenKBLib);
            GroupTools = new RibbonGroup(ribbon, Cmd.cmdGroupTools);
            ButtonToggleTheme = new RibbonButton(ribbon, Cmd.cmdButtonToggleTheme);
            TabMain = new RibbonTab(ribbon, Cmd.cmdTabMain);
            GroupMain = new RibbonGroup(ribbon, Cmd.cmdGroupMain);
            GroupWorkTools = new RibbonGroup(ribbon, Cmd.cmdGroupWorkTools);
            TabInformation = new RibbonTab(ribbon, Cmd.cmdTabInformation);
            GroupInformation = new RibbonGroup(ribbon, Cmd.cmdGroupInformation);
        }

    }
}
