//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using RibbonLib;
using RibbonLib.Controls;

namespace RibbonLib.Controls
{
    partial class RibbonItems
    {
        private static class Cmd
        {
            public const uint cmdMenuResearchWork = 3;
            public const uint cmdTabResearchWork = 5;
            public const uint cmdGroupResearchWork = 4;
            public const uint cmdButtonOpenKb = 2;
            public const uint cmdTabMain = 9;
            public const uint cmdGroupMain = 7;
            public const uint cmdButtonOpenResearch = 6;
        }

        // ContextPopup CommandName

        public Ribbon Ribbon { get; private set; }
        public RibbonTabGroup MenuResearchWork { get; private set; }
        public RibbonTab TabResearchWork { get; private set; }
        public RibbonGroup GroupResearchWork { get; private set; }
        public RibbonButton ButtonOpenKb { get; private set; }
        public RibbonTab TabMain { get; private set; }
        public RibbonGroup GroupMain { get; private set; }
        public RibbonButton ButtonOpenResearch { get; private set; }

        public RibbonItems(Ribbon ribbon)
        {
            if (ribbon == null)
                throw new ArgumentNullException(nameof(ribbon), "Parameter is null");
            this.Ribbon = ribbon;
            MenuResearchWork = new RibbonTabGroup(ribbon, Cmd.cmdMenuResearchWork);
            TabResearchWork = new RibbonTab(ribbon, Cmd.cmdTabResearchWork);
            GroupResearchWork = new RibbonGroup(ribbon, Cmd.cmdGroupResearchWork);
            ButtonOpenKb = new RibbonButton(ribbon, Cmd.cmdButtonOpenKb);
            TabMain = new RibbonTab(ribbon, Cmd.cmdTabMain);
            GroupMain = new RibbonGroup(ribbon, Cmd.cmdGroupMain);
            ButtonOpenResearch = new RibbonButton(ribbon, Cmd.cmdButtonOpenResearch);
        }

    }
}
