'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports RibbonLib
Imports RibbonLib.Controls

Namespace RibbonLib.Controls
    Partial Class RibbonItems
        Private Class Cmd
            Public Const cmdButtonOpenFolder As UInteger = 16
            Public Const cmdButtonOpenResearch As UInteger = 6
            Public Const cmdMenuTools As UInteger = 24
            Public Const cmdButtonOpenConsole As UInteger = 22
            Public Const cmdButtonVennTool As UInteger = 23
            Public Const cmdButtonLLMTool As UInteger = 25
            Public Const cmdButtonSettings As UInteger = 38
            Public Const cmdButtonLicense As UInteger = 18
            Public Const cmdButtonExit As UInteger = 17
            Public Const cmdMenuResearchWork As UInteger = 3
            Public Const cmdTabResearchWork As UInteger = 5
            Public Const cmdGroupResearchWork As UInteger = 4
            Public Const cmdButtonOpenKb As UInteger = 2
            Public Const cmdButtonDataset As UInteger = 26
            Public Const cmdButtonEditResearchTopic As UInteger = 42
            Public Const cmdGroupResearchAgentWork As UInteger = 27
            Public Const cmdButtonStart As UInteger = 28
            Public Const cmdMenuKBLib As UInteger = 12
            Public Const cmdTabKBLib As UInteger = 11
            Public Const cmdGroupKBLib As UInteger = 13
            Public Const cmdBtnOpenKBLib As UInteger = 10
            Public Const cmdGroupTools As UInteger = 14
            Public Const cmdButtonToggleTheme As UInteger = 15
            Public Const cmdMenuDataSet As UInteger = 29
            Public Const cmdTabDataSet As UInteger = 30
            Public Const cmdGroupDataSet As UInteger = 31
            Public Const cmdButtonLoadDataSet As UInteger = 32
            Public Const cmdButtonSaveDataSet As UInteger = 33
            Public Const cmdButtonSaveAsDataSet As UInteger = 34
            Public Const cmdButtonDataSetToggleOmics As UInteger = 37
            Public Const cmdButtonPreviewDataset As UInteger = 35
            Public Const cmdButtonDataSetEditorToggleTheme As UInteger = 36
            Public Const cmdTabMain As UInteger = 9
            Public Const cmdGroupMain As UInteger = 7
            Public Const cmdGroupWorkTools As UInteger = 21
            Public Const cmdGroupWorkbench As UInteger = 40
            Public Const cmdButtonStartPage As UInteger = 39
            Public Const cmdButtonOpenOutput As UInteger = 41
            Public Const cmdTabInformation As UInteger = 19
            Public Const cmdGroupInformation As UInteger = 20
        End Class

        ' ContextPopup CommandName

        Private _ribbon As Ribbon
        Public ReadOnly Property Ribbon As Ribbon
            Get
                Return _ribbon
            End Get
        End Property
        Private _ButtonOpenFolder As RibbonButton
        Public ReadOnly Property ButtonOpenFolder As RibbonButton
            Get
                Return _ButtonOpenFolder
            End Get
        End Property
        Private _ButtonOpenResearch As RibbonButton
        Public ReadOnly Property ButtonOpenResearch As RibbonButton
            Get
                Return _ButtonOpenResearch
            End Get
        End Property
        Private _MenuTools As RibbonDropDownButton
        Public ReadOnly Property MenuTools As RibbonDropDownButton
            Get
                Return _MenuTools
            End Get
        End Property
        Private _ButtonOpenConsole As RibbonButton
        Public ReadOnly Property ButtonOpenConsole As RibbonButton
            Get
                Return _ButtonOpenConsole
            End Get
        End Property
        Private _ButtonVennTool As RibbonButton
        Public ReadOnly Property ButtonVennTool As RibbonButton
            Get
                Return _ButtonVennTool
            End Get
        End Property
        Private _ButtonLLMTool As RibbonButton
        Public ReadOnly Property ButtonLLMTool As RibbonButton
            Get
                Return _ButtonLLMTool
            End Get
        End Property
        Private _ButtonSettings As RibbonButton
        Public ReadOnly Property ButtonSettings As RibbonButton
            Get
                Return _ButtonSettings
            End Get
        End Property
        Private _ButtonLicense As RibbonButton
        Public ReadOnly Property ButtonLicense As RibbonButton
            Get
                Return _ButtonLicense
            End Get
        End Property
        Private _ButtonExit As RibbonButton
        Public ReadOnly Property ButtonExit As RibbonButton
            Get
                Return _ButtonExit
            End Get
        End Property
        Private _MenuResearchWork As RibbonTabGroup
        Public ReadOnly Property MenuResearchWork As RibbonTabGroup
            Get
                Return _MenuResearchWork
            End Get
        End Property
        Private _TabResearchWork As RibbonTab
        Public ReadOnly Property TabResearchWork As RibbonTab
            Get
                Return _TabResearchWork
            End Get
        End Property
        Private _GroupResearchWork As RibbonGroup
        Public ReadOnly Property GroupResearchWork As RibbonGroup
            Get
                Return _GroupResearchWork
            End Get
        End Property
        Private _ButtonOpenKb As RibbonButton
        Public ReadOnly Property ButtonOpenKb As RibbonButton
            Get
                Return _ButtonOpenKb
            End Get
        End Property
        Private _ButtonDataset As RibbonButton
        Public ReadOnly Property ButtonDataset As RibbonButton
            Get
                Return _ButtonDataset
            End Get
        End Property
        Private _ButtonEditResearchTopic As RibbonButton
        Public ReadOnly Property ButtonEditResearchTopic As RibbonButton
            Get
                Return _ButtonEditResearchTopic
            End Get
        End Property
        Private _GroupResearchAgentWork As RibbonGroup
        Public ReadOnly Property GroupResearchAgentWork As RibbonGroup
            Get
                Return _GroupResearchAgentWork
            End Get
        End Property
        Private _ButtonStart As RibbonButton
        Public ReadOnly Property ButtonStart As RibbonButton
            Get
                Return _ButtonStart
            End Get
        End Property
        Private _MenuKBLib As RibbonTabGroup
        Public ReadOnly Property MenuKBLib As RibbonTabGroup
            Get
                Return _MenuKBLib
            End Get
        End Property
        Private _TabKBLib As RibbonTab
        Public ReadOnly Property TabKBLib As RibbonTab
            Get
                Return _TabKBLib
            End Get
        End Property
        Private _GroupKBLib As RibbonGroup
        Public ReadOnly Property GroupKBLib As RibbonGroup
            Get
                Return _GroupKBLib
            End Get
        End Property
        Private _BtnOpenKBLib As RibbonButton
        Public ReadOnly Property BtnOpenKBLib As RibbonButton
            Get
                Return _BtnOpenKBLib
            End Get
        End Property
        Private _GroupTools As RibbonGroup
        Public ReadOnly Property GroupTools As RibbonGroup
            Get
                Return _GroupTools
            End Get
        End Property
        Private _ButtonToggleTheme As RibbonButton
        Public ReadOnly Property ButtonToggleTheme As RibbonButton
            Get
                Return _ButtonToggleTheme
            End Get
        End Property
        Private _MenuDataSet As RibbonTabGroup
        Public ReadOnly Property MenuDataSet As RibbonTabGroup
            Get
                Return _MenuDataSet
            End Get
        End Property
        Private _TabDataSet As RibbonTab
        Public ReadOnly Property TabDataSet As RibbonTab
            Get
                Return _TabDataSet
            End Get
        End Property
        Private _GroupDataSet As RibbonGroup
        Public ReadOnly Property GroupDataSet As RibbonGroup
            Get
                Return _GroupDataSet
            End Get
        End Property
        Private _ButtonLoadDataSet As RibbonButton
        Public ReadOnly Property ButtonLoadDataSet As RibbonButton
            Get
                Return _ButtonLoadDataSet
            End Get
        End Property
        Private _ButtonSaveDataSet As RibbonButton
        Public ReadOnly Property ButtonSaveDataSet As RibbonButton
            Get
                Return _ButtonSaveDataSet
            End Get
        End Property
        Private _ButtonSaveAsDataSet As RibbonButton
        Public ReadOnly Property ButtonSaveAsDataSet As RibbonButton
            Get
                Return _ButtonSaveAsDataSet
            End Get
        End Property
        Private _ButtonDataSetToggleOmics As RibbonButton
        Public ReadOnly Property ButtonDataSetToggleOmics As RibbonButton
            Get
                Return _ButtonDataSetToggleOmics
            End Get
        End Property
        Private _ButtonPreviewDataset As RibbonButton
        Public ReadOnly Property ButtonPreviewDataset As RibbonButton
            Get
                Return _ButtonPreviewDataset
            End Get
        End Property
        Private _ButtonDataSetEditorToggleTheme As RibbonButton
        Public ReadOnly Property ButtonDataSetEditorToggleTheme As RibbonButton
            Get
                Return _ButtonDataSetEditorToggleTheme
            End Get
        End Property
        Private _TabMain As RibbonTab
        Public ReadOnly Property TabMain As RibbonTab
            Get
                Return _TabMain
            End Get
        End Property
        Private _GroupMain As RibbonGroup
        Public ReadOnly Property GroupMain As RibbonGroup
            Get
                Return _GroupMain
            End Get
        End Property
        Private _GroupWorkTools As RibbonGroup
        Public ReadOnly Property GroupWorkTools As RibbonGroup
            Get
                Return _GroupWorkTools
            End Get
        End Property
        Private _GroupWorkbench As RibbonGroup
        Public ReadOnly Property GroupWorkbench As RibbonGroup
            Get
                Return _GroupWorkbench
            End Get
        End Property
        Private _ButtonStartPage As RibbonButton
        Public ReadOnly Property ButtonStartPage As RibbonButton
            Get
                Return _ButtonStartPage
            End Get
        End Property
        Private _ButtonOpenOutput As RibbonButton
        Public ReadOnly Property ButtonOpenOutput As RibbonButton
            Get
                Return _ButtonOpenOutput
            End Get
        End Property
        Private _TabInformation As RibbonTab
        Public ReadOnly Property TabInformation As RibbonTab
            Get
                Return _TabInformation
            End Get
        End Property
        Private _GroupInformation As RibbonGroup
        Public ReadOnly Property GroupInformation As RibbonGroup
            Get
                Return _GroupInformation
            End Get
        End Property

        Public Sub New(ByVal ribbon As Ribbon)
            If ribbon Is Nothing Then
                Throw New ArgumentNullException(NameOf(ribbon), "Parameter is Nothing")
            End If
            _ribbon = ribbon
            _ButtonOpenFolder = New RibbonButton(_ribbon, Cmd.cmdButtonOpenFolder)
            _ButtonOpenResearch = New RibbonButton(_ribbon, Cmd.cmdButtonOpenResearch)
            _MenuTools = New RibbonDropDownButton(_ribbon, Cmd.cmdMenuTools)
            _ButtonOpenConsole = New RibbonButton(_ribbon, Cmd.cmdButtonOpenConsole)
            _ButtonVennTool = New RibbonButton(_ribbon, Cmd.cmdButtonVennTool)
            _ButtonLLMTool = New RibbonButton(_ribbon, Cmd.cmdButtonLLMTool)
            _ButtonSettings = New RibbonButton(_ribbon, Cmd.cmdButtonSettings)
            _ButtonLicense = New RibbonButton(_ribbon, Cmd.cmdButtonLicense)
            _ButtonExit = New RibbonButton(_ribbon, Cmd.cmdButtonExit)
            _MenuResearchWork = New RibbonTabGroup(_ribbon, Cmd.cmdMenuResearchWork)
            _TabResearchWork = New RibbonTab(_ribbon, Cmd.cmdTabResearchWork)
            _GroupResearchWork = New RibbonGroup(_ribbon, Cmd.cmdGroupResearchWork)
            _ButtonOpenKb = New RibbonButton(_ribbon, Cmd.cmdButtonOpenKb)
            _ButtonDataset = New RibbonButton(_ribbon, Cmd.cmdButtonDataset)
            _ButtonEditResearchTopic = New RibbonButton(_ribbon, Cmd.cmdButtonEditResearchTopic)
            _GroupResearchAgentWork = New RibbonGroup(_ribbon, Cmd.cmdGroupResearchAgentWork)
            _ButtonStart = New RibbonButton(_ribbon, Cmd.cmdButtonStart)
            _MenuKBLib = New RibbonTabGroup(_ribbon, Cmd.cmdMenuKBLib)
            _TabKBLib = New RibbonTab(_ribbon, Cmd.cmdTabKBLib)
            _GroupKBLib = New RibbonGroup(_ribbon, Cmd.cmdGroupKBLib)
            _BtnOpenKBLib = New RibbonButton(_ribbon, Cmd.cmdBtnOpenKBLib)
            _GroupTools = New RibbonGroup(_ribbon, Cmd.cmdGroupTools)
            _ButtonToggleTheme = New RibbonButton(_ribbon, Cmd.cmdButtonToggleTheme)
            _MenuDataSet = New RibbonTabGroup(_ribbon, Cmd.cmdMenuDataSet)
            _TabDataSet = New RibbonTab(_ribbon, Cmd.cmdTabDataSet)
            _GroupDataSet = New RibbonGroup(_ribbon, Cmd.cmdGroupDataSet)
            _ButtonLoadDataSet = New RibbonButton(_ribbon, Cmd.cmdButtonLoadDataSet)
            _ButtonSaveDataSet = New RibbonButton(_ribbon, Cmd.cmdButtonSaveDataSet)
            _ButtonSaveAsDataSet = New RibbonButton(_ribbon, Cmd.cmdButtonSaveAsDataSet)
            _ButtonDataSetToggleOmics = New RibbonButton(_ribbon, Cmd.cmdButtonDataSetToggleOmics)
            _ButtonPreviewDataset = New RibbonButton(_ribbon, Cmd.cmdButtonPreviewDataset)
            _ButtonDataSetEditorToggleTheme = New RibbonButton(_ribbon, Cmd.cmdButtonDataSetEditorToggleTheme)
            _TabMain = New RibbonTab(_ribbon, Cmd.cmdTabMain)
            _GroupMain = New RibbonGroup(_ribbon, Cmd.cmdGroupMain)
            _GroupWorkTools = New RibbonGroup(_ribbon, Cmd.cmdGroupWorkTools)
            _GroupWorkbench = New RibbonGroup(_ribbon, Cmd.cmdGroupWorkbench)
            _ButtonStartPage = New RibbonButton(_ribbon, Cmd.cmdButtonStartPage)
            _ButtonOpenOutput = New RibbonButton(_ribbon, Cmd.cmdButtonOpenOutput)
            _TabInformation = New RibbonTab(_ribbon, Cmd.cmdTabInformation)
            _GroupInformation = New RibbonGroup(_ribbon, Cmd.cmdGroupInformation)
        End Sub

    End Class
End Namespace
